spring:
  #  local development cred
  config:
    import: optional:local-cred.yml

  application:
    name: smartexpensetracker

  server:
    port: 8080

  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    driverClassName: org.postgresql.Driver
    hikari:
      schema: postgres

  # datasource:
  #   url: jdbc:mysql://localhost:3306/ump_transaction
  #   driverClassName: com.mysql.cj.jdbc.Driver
  #   hikari:
  #     schema: ump_transaction

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/structure, classpath:db/migration/data # the location where flyway should look for migration scripts
    validate-on-migrate: true
    default-schema: ump_transaction

  logging:
    level:
      org.flywaydb: DEBUG
