spring:
  #  local development cred
  config:
    import: optional:local-cred.yml

  application:
    name: smartexpensetracker

  server:
    port: 8080

  datasource:
    driverClassName: org.postgresql.Driver
    hikari:
      schema: ump_transaction

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration/structure, classpath:db/migration/data # the location where flyway should look for migration scripts
    validate-on-migrate: true
    default-schema: ump_transaction
    schemas: public
    table: flyway_schema_history
    baseline-description: true

  logging:
    level:
      org.flywaydb: DEBUG
